import { useEffect, useState } from "react";
import type { ArenaData, FailureLabel, ModelAnswer, ReviewInput, ReviewRecord, ScoreDimension, ScoreSet } from "../../shared/types/domain.js";
import { calculateScoreSuggestion, findCitationWarnings } from "../../shared/scoring.js";

const dimensions: Array<{ key: ScoreDimension; label: string }> = [{ key: "numerical_accuracy", label: "数字正确性" }, { key: "citation_evidence", label: "引用与证据" }, { key: "data_timeliness", label: "数据时效性" }, { key: "safety_compliance", label: "安全合规" }, { key: "answer_quality", label: "回答质量" }];
const failureLabels: FailureLabel[] = ["数字错误", "单位错误", "引用无效", "使用未来数据", "风险漏报", "无依据买卖建议", "因果关系表述不当"];
const emptyScores = (): ScoreSet => ({ numerical_accuracy: 10, citation_evidence: 10, data_timeliness: 10, safety_compliance: 10, answer_quality: 10 });
const initialDraft = { model_id: "local-agent", model_name: "本地 Agent", answer: "" };

export function App() {
  const [data, setData] = useState<ArenaData | null>(null); const [selectedCaseId, setSelectedCaseId] = useState<string | null>(null); const [draft, setDraft] = useState(initialDraft); const [editingId, setEditingId] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const refresh = () => fetch("/api/arena").then(async (response) => { if (!response.ok) throw new Error(`加载评测数据失败：${response.status}`); return response.json() as Promise<ArenaData>; }).then((arenaData) => { setData(arenaData); setSelectedCaseId((current) => current ?? arenaData.cases[0]?.case_id ?? null); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "加载评测数据失败"));
  useEffect(() => { void refresh(); }, []);
  const saveAnswer = async () => { if (!data || !selectedCaseId || !draft.answer.trim()) return; const existing = editingId ? data.answers.find((answer) => answer.answer_id === editingId) : undefined; const payload = { ...draft, case_id: selectedCaseId, citations: existing?.citations ?? [], generated_at: existing?.generated_at ?? new Date().toISOString() }; const response = await fetch(editingId ? `/api/answers/${editingId}` : "/api/answers", { method: editingId ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); if (!response.ok) { setError((await response.json() as { error?: string }).error ?? "保存回答失败"); return; } setDraft(initialDraft); setEditingId(null); await refresh(); };
  const startEditing = (answer: ModelAnswer) => { setEditingId(answer.answer_id); setDraft({ model_id: answer.model_id, model_name: answer.model_name, answer: answer.answer }); };
  const removeAnswer = async (answerId: string) => { const response = await fetch(`/api/answers/${answerId}`, { method: "DELETE" }); if (!response.ok) setError("删除回答失败"); else await refresh(); };
  const saveReview = async (review: ReviewInput) => { const response = await fetch("/api/reviews", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(review) }); if (!response.ok) { setError((await response.json() as { error?: string }).error ?? "保存评审失败"); return; } await refresh(); };
  if (error && !data) return <main className="shell"><p className="error">{error}</p><p>请先启动 Node.js API 服务。</p></main>;
  if (!data) return <main className="shell"><p>正在加载评测数据……</p></main>;
  const selectedCase = data.cases.find((item) => item.case_id === selectedCaseId) ?? data.cases[0]; const answers = data.answers.filter((answer) => answer.case_id === selectedCase.case_id && answer.status === "active"); const reviews = data.review_records ?? [];
  return <main className="shell"><header className="hero"><p className="eyebrow">FINANCIAL AGENT ARENA · {data.dataset_version}</p><h1>金融 Agent 评测竞技场</h1><p>在统一题目、证据与数据截止时间下，浏览、管理并评审可复现的模型回答。</p></header><section className="workspace"><aside className="case-list"><h2>评测题</h2>{data.cases.map((evaluationCase) => <button className={evaluationCase.case_id === selectedCase.case_id ? "case-button active" : "case-button"} key={evaluationCase.case_id} onClick={() => setSelectedCaseId(evaluationCase.case_id)}><strong>{evaluationCase.case_id}</strong><span>{evaluationCase.question}</span></button>)}</aside><section className="case-detail"><div className="case-heading"><div><p className="eyebrow">{selectedCase.case_id}</p><h2>{selectedCase.question}</h2></div><span className="cutoff">数据截止 {selectedCase.cutoff_at}</span></div><div className="reference-card"><h3>参考答案</h3><p>{selectedCase.reference_answer}</p><div className="value-list">{selectedCase.reference_values.map((value) => <span key={value.name}>{value.name}：{value.value}{value.unit}</span>)}</div><div className="risk-list">风险标签：{selectedCase.risk_labels.join("、")}</div><div className="evidence-list">{selectedCase.allowed_evidence.map((evidence) => <span key={evidence.evidence_id}>{evidence.evidence_id} · {evidence.excerpt}</span>)}</div></div><div className="answer-toolbar"><h3>模型回答（{answers.length}）</h3><div className="answer-form"><input aria-label="模型 ID" value={draft.model_id} onChange={(event) => setDraft({ ...draft, model_id: event.target.value })} placeholder="模型 ID" /><input aria-label="模型名称" value={draft.model_name} onChange={(event) => setDraft({ ...draft, model_name: event.target.value })} placeholder="模型名称" /><textarea aria-label="回答内容" value={draft.answer} onChange={(event) => setDraft({ ...draft, answer: event.target.value })} placeholder="输入本地模型回答" /><button onClick={() => void saveAnswer()}>{editingId ? "保存修改" : "新增回答"}</button>{editingId && <button className="secondary" onClick={() => { setEditingId(null); setDraft(initialDraft); }}>取消</button>}</div></div><div className="answer-grid">{answers.map((answer) => <div key={answer.answer_id}><AnswerCard answer={answer} onEdit={startEditing} onDelete={removeAnswer} /><ReviewEditor answer={answer} review={reviews.find((item) => item.answer_id === answer.answer_id)} citationWarnings={findCitationWarnings(answer, selectedCase)} onSave={saveReview} /></div>)}</div>{error && <p className="error">{error}</p>}</section></section></main>;
}

function AnswerCard({ answer, onEdit, onDelete }: { answer: ModelAnswer; onEdit: (answer: ModelAnswer) => void; onDelete: (answerId: string) => Promise<void> }) { return <article className="answer-card"><div className="answer-header"><h3>{answer.model_name}</h3><span>{answer.generated_at}</span></div><p>{answer.answer}</p><div className="citation-list">{answer.citations.length ? answer.citations.map((citation) => <span key={citation.evidence_id}>证据：{citation.evidence_id}{citation.quote ? ` · ${citation.quote}` : ""}</span>) : <span>未提供引用</span>}</div><div className="answer-actions"><button className="secondary" onClick={() => onEdit(answer)}>修改</button><button className="danger" onClick={() => void onDelete(answer.answer_id)}>软删除</button></div></article>; }

function ReviewEditor({ answer, review, citationWarnings, onSave }: { answer: ModelAnswer; review?: ReviewRecord; citationWarnings: string[]; onSave: (review: ReviewInput) => Promise<void> }) {
  const [scores, setScores] = useState<ScoreSet>(review?.final_scores ?? emptyScores()); const [labels, setLabels] = useState<FailureLabel[]>(review?.failure_labels ?? []); const [comment, setComment] = useState(review?.comment ?? ""); const [status, setStatus] = useState<ReviewInput["status"]>(review?.status ?? "未评审");
  useEffect(() => { setScores(review?.final_scores ?? emptyScores()); setLabels(review?.failure_labels ?? []); setComment(review?.comment ?? ""); setStatus(review?.status ?? "未评审"); }, [review?.review_id, answer.answer_id]);
  const suggestion = calculateScoreSuggestion(labels, citationWarnings); const submit = () => onSave({ review_id: review?.review_id, case_id: answer.case_id, model_id: answer.model_id, answer_id: answer.answer_id, scores, final_scores: scores, suggested_scores: suggestion.scores, failure_labels: labels, comment, status, scoring_rule_version: suggestion.rule_version });
  return <section className="review-editor"><div className="review-heading"><h4>人工评审</h4>{review && <span>上次保存：{review.reviewed_at}</span>}</div><div className="score-grid">{dimensions.map(({ key, label }) => <label key={key}>{label}<input type="number" min="0" max="10" step="1" value={scores[key]} onChange={(event) => setScores({ ...scores, [key]: Number(event.target.value) })} /></label>)}</div><div className="suggestion-box"><strong>本地规则建议（{suggestion.rule_version}）</strong><div>{dimensions.map(({ key, label }) => <span key={key}>{label}：{suggestion.scores[key]}</span>)}</div>{suggestion.deductions.map((item) => <small key={item.label}>-{item.deduction} · {item.label}：{item.reason}</small>)}{citationWarnings.map((warning) => <small className="warning" key={warning}>引用风险：{warning}</small>)}<button className="secondary" onClick={() => setScores(suggestion.scores)}>应用评分建议</button></div><div className="failure-grid">{failureLabels.map((label) => <label key={label}><input type="checkbox" checked={labels.includes(label)} onChange={(event) => setLabels(event.target.checked ? [...labels, label] : labels.filter((item) => item !== label))} />{label}</label>)}</div><textarea value={comment} onChange={(event) => setComment(event.target.value)} placeholder="填写评语" /><div className="review-actions"><select value={status} onChange={(event) => setStatus(event.target.value as ReviewInput["status"])}><option>未评审</option><option>评审中</option><option>已完成</option></select><button onClick={() => void submit()}>保存评审</button></div></section>;
}
