import { useRef, useState } from "react";
import type { ArenaData } from "../../shared/types/domain.js";

export function DataTransfer({ onImported }: { onImported: () => Promise<unknown> | void }) {
  const inputRef = useRef<HTMLInputElement>(null); const [message, setMessage] = useState("");
  const exportJson = async () => { const response = await fetch("/api/export"); const blob = new Blob([JSON.stringify(await response.json(), null, 2)], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "financial-agent-arena-export.json"; link.click(); URL.revokeObjectURL(link.href); setMessage("已导出 JSON 快照"); };
  const importJson = async (file: File) => { try { const payload = JSON.parse(await file.text()) as ArenaData; const previewResponse = await fetch("/api/import/preview", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); if (!previewResponse.ok) throw new Error((await previewResponse.json() as { error?: string }).error ?? "格式校验失败"); const summary = (await previewResponse.json() as { summary: { cases: number; answers: number; reviews: number } }).summary; if (!window.confirm(`确认整体替换本地数据？题目 ${summary.cases}，回答 ${summary.answers}，评审 ${summary.reviews}`)) return; const response = await fetch("/api/import", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error((await response.json() as { error?: string }).error ?? "导入失败"); await onImported(); setMessage("已导入并整体替换本地数据"); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "导入失败"); } finally { if (inputRef.current) inputRef.current.value = ""; } };
  return <div className="data-transfer"><button className="secondary" onClick={() => void exportJson()}>导出 JSON</button><button className="secondary" onClick={() => inputRef.current?.click()}>导入 JSON</button><input ref={inputRef} type="file" accept="application/json" hidden onChange={(event) => { const file = event.target.files?.[0]; if (file) void importJson(file); }} />{message && <small>{message}</small>}</div>;
}
