import { randomUUID } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { ArenaData, EvaluationCase, FailureLabel, ModelAnswer, ReviewInput, ReviewRecord, ReviewStatus, ScoreSet } from "../../shared/types/domain.js";
import { failureLabels, scoreDimensions } from "../../shared/types/domain.js";
import { calculateScoreSuggestion, findCitationWarnings, type ScoreSuggestion } from "../../shared/scoring.js";
import type { ReviewQueueItem } from "../../shared/filters.js";

export const defaultFixturePath = resolve(process.cwd(), "data/fixtures/arena-data.json");
export type NewModelAnswer = Omit<ModelAnswer, "answer_id" | "status">;
export type ModelAnswerPatch = Partial<NewModelAnswer>;
const reviewStatuses: readonly ReviewStatus[] = ["未评审", "评审中", "已完成"];
function assertUtcTimestamp(value: string, field: string): void { if (!value.endsWith("Z")) throw new Error(`${field} must be an ISO 8601 UTC timestamp`); }
function assertScoreSet(scores: ScoreSet, field: string): void { for (const dimension of scoreDimensions) { const value = scores?.[dimension]; if (typeof value !== "number" || !Number.isFinite(value) || value < 0 || value > 10) throw new Error(`${field}.${dimension} must be between 0 and 10`); } }
function validateData(data: ArenaData): ArenaData {
  if (!Array.isArray(data.cases) || data.cases.length < 5) throw new Error("The fixture must contain at least five evaluation cases");
  const caseIds = new Set<string>();
  for (const evaluationCase of data.cases) { if (!evaluationCase.case_id || caseIds.has(evaluationCase.case_id)) throw new Error(`Invalid or duplicate case_id: ${evaluationCase.case_id}`); caseIds.add(evaluationCase.case_id); assertUtcTimestamp(evaluationCase.cutoff_at, `${evaluationCase.case_id}.cutoff_at`); if (!evaluationCase.allowed_evidence.length) throw new Error(`${evaluationCase.case_id} must contain allowed evidence`); }
  const answerIds = new Set<string>();
  for (const answer of data.answers) { if (answerIds.has(answer.answer_id) || !caseIds.has(answer.case_id) || !answer.answer.trim()) throw new Error(`Invalid or duplicate model answer: ${answer.answer_id}`); if (answer.status !== "active" && answer.status !== "inactive") throw new Error(`Invalid answer status: ${answer.answer_id}`); answerIds.add(answer.answer_id); assertUtcTimestamp(answer.generated_at, `${answer.answer_id}.generated_at`); }
  for (const review of data.review_records ?? []) { const answer = data.answers.find((item) => item.answer_id === review.answer_id); if (!answer || answer.case_id !== review.case_id || answer.model_id !== review.model_id) throw new Error(`Invalid review answer_id: ${review.review_id}`); assertScoreSet(review.scores, `${review.review_id}.scores`); assertScoreSet(review.final_scores, `${review.review_id}.final_scores`); if (review.failure_labels.some((label) => !(failureLabels as readonly string[]).includes(label))) throw new Error(`Invalid failure label: ${review.review_id}`); if (!reviewStatuses.includes(review.status)) throw new Error(`Invalid review status: ${review.review_id}`); assertUtcTimestamp(review.reviewed_at, `${review.review_id}.reviewed_at`); }
  return data;
}
export function loadArenaData(filePath = defaultFixturePath): ArenaData { return validateData(JSON.parse(readFileSync(filePath, "utf8")) as ArenaData); }
export type ArenaServiceOptions = { persistPath?: string };
export type ArenaService = { getSnapshot(): ArenaData; listCases(): EvaluationCase[]; listAnswers(caseId: string): ModelAnswer[]; addAnswer(input: NewModelAnswer): ModelAnswer; updateAnswer(answerId: string, patch: ModelAnswerPatch): ModelAnswer; deactivateAnswer(answerId: string): ModelAnswer; listReviews(): ReviewRecord[]; getReview(caseId: string, modelId: string): ReviewRecord | undefined; listReviewQueue(): ReviewQueueItem[]; saveReview(input: ReviewInput): ReviewRecord; getScoreSuggestion(labels: FailureLabel[]): ScoreSuggestion; getCitationWarnings(answerId: string): string[]; applyScoreSuggestion(reviewId: string): ReviewRecord };
export function createArenaService(data = loadArenaData(), options: ArenaServiceOptions = {}): ArenaService {
  const mutableData = structuredClone(data); mutableData.review_records ??= []; validateData(mutableData);
  const persist = () => { if (options.persistPath) writeFileSync(options.persistPath, `${JSON.stringify(mutableData, null, 2)}\n`, "utf8"); };
  const findAnswer = (answerId: string): ModelAnswer => { const answer = mutableData.answers.find((item) => item.answer_id === answerId); if (!answer) throw new Error(`Unknown answer_id: ${answerId}`); return answer; };
  const deactivateOtherActiveAnswers = (modelId: string, caseId: string, exceptAnswerId?: string) => { for (const answer of mutableData.answers) if (answer.case_id === caseId && answer.model_id === modelId && answer.answer_id !== exceptAnswerId) answer.status = "inactive"; };
  const validateReview = (input: ReviewInput) => { const answer = findAnswer(input.answer_id); if (answer.case_id !== input.case_id || answer.model_id !== input.model_id) throw new Error("Review must reference the answer's case and model"); assertScoreSet(input.scores, "scores"); assertScoreSet(input.final_scores, "final_scores"); if (input.failure_labels.some((label) => !(failureLabels as readonly string[]).includes(label))) throw new Error("Invalid failure label"); if (!reviewStatuses.includes(input.status)) throw new Error("Invalid review status"); };
  return {
    getSnapshot: () => structuredClone(mutableData), listCases: () => structuredClone(mutableData.cases), listAnswers: (caseId) => structuredClone(mutableData.answers.filter((answer) => answer.case_id === caseId && answer.status === "active")),
    addAnswer: (input) => { if (!mutableData.cases.some((evaluationCase) => evaluationCase.case_id === input.case_id)) throw new Error(`Unknown case_id: ${input.case_id}`); if (!input.answer.trim()) throw new Error("answer must not be empty"); assertUtcTimestamp(input.generated_at, "generated_at"); deactivateOtherActiveAnswers(input.model_id, input.case_id); const answer: ModelAnswer = { ...structuredClone(input), answer_id: `answer-${randomUUID()}`, status: "active" }; mutableData.answers.push(answer); persist(); return structuredClone(answer); },
    updateAnswer: (answerId, patch) => { const current = findAnswer(answerId); const updated: ModelAnswer = { ...current, ...structuredClone(patch), answer_id: current.answer_id, status: current.status }; if (!updated.answer.trim()) throw new Error("answer must not be empty"); assertUtcTimestamp(updated.generated_at, "generated_at"); if (updated.status === "active") deactivateOtherActiveAnswers(updated.model_id, updated.case_id, answerId); Object.assign(current, updated); persist(); return structuredClone(current); },
    deactivateAnswer: (answerId) => { const answer = findAnswer(answerId); answer.status = "inactive"; persist(); return structuredClone(answer); },
    listReviews: () => structuredClone(mutableData.review_records ?? []), getReview: (caseId, modelId) => { const matches = (mutableData.review_records ?? []).filter((review) => review.case_id === caseId && review.model_id === modelId); return matches.length ? structuredClone(matches[matches.length - 1]) : undefined; },
    listReviewQueue: () => structuredClone(mutableData.answers.filter((answer) => answer.status === "active").map((answer): ReviewQueueItem => { const matches = (mutableData.review_records ?? []).filter((review) => review.answer_id === answer.answer_id); const review = matches.length ? matches[matches.length - 1] : undefined; return { case_id: answer.case_id, model_id: answer.model_id, answer_id: answer.answer_id, status: review?.status ?? "未评审", failure_labels: review?.failure_labels ?? [], review }; })),
    saveReview: (input) => { validateReview(input); const records = mutableData.review_records ?? (mutableData.review_records = []); const existingIndex = input.review_id ? records.findIndex((review) => review.review_id === input.review_id) : records.findIndex((review) => review.case_id === input.case_id && review.model_id === input.model_id && review.answer_id === input.answer_id); const record: ReviewRecord = { ...structuredClone(input), review_id: input.review_id ?? `review-${randomUUID()}`, reviewed_at: new Date().toISOString() }; if (existingIndex >= 0) records[existingIndex] = record; else records.push(record); persist(); return structuredClone(record); },
    getScoreSuggestion: (labels) => calculateScoreSuggestion(labels), getCitationWarnings: (answerId) => { const answer = findAnswer(answerId); const evaluationCase = mutableData.cases.find((item) => item.case_id === answer.case_id)!; return findCitationWarnings(answer, evaluationCase); }, applyScoreSuggestion: (reviewId) => { const review = (mutableData.review_records ?? []).find((item) => item.review_id === reviewId); if (!review) throw new Error(`Unknown review_id: ${reviewId}`); const suggestion = calculateScoreSuggestion(review.failure_labels); review.suggested_scores = suggestion.scores; review.final_scores = structuredClone(suggestion.scores); review.scoring_rule_version = suggestion.rule_version; review.reviewed_at = new Date().toISOString(); persist(); return structuredClone(review); },
  };
}
